web_calendar/web_calendar/Models/Calendar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;

namespace web_calendar.Models
{
    public class Calendar
    {
        public string Name { get; set; }
        public string Text { get; set; }
        public  Color color { get; set; }
        //public List<Events> { get; set; }
        bool _visibility { get; set; }
        string _timezone {get; set; }
        int _userId {get; set; }
        //NotificationType _notificationType { get; set; }
    }
}

web_calendar/web_calendar/Models/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace web_calendar.Models
{
    public class CalendarViewModel
    {
        public int CalendarViewId { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Color")]
        public string CalendarColor { get; set; }

        [Display(Name = "Visibility")]
        public string Visibility { get; set; }

        [Display(Name = "Time zone")]
        public byte? TimeZone { get; set; }

        // Notification Settings
        public NotificationSettingsViewModel notificationSettings { get; set; }        

        string _userId {get; set; }
    }
}

web_calendar/web_calendar/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_calendar.DAL.Interface;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;
using web_calendar.DAL.Models;
using web_calendar.Models;
using System.Net;
using web_calendar.BL.ViewModels;
using web_calendar.BL.Mappers;
using web_calendar.BL.DomainModels;

namespace web_calendar.Controllers
{
    [Authorize]
    public class CalendarController : Controller
    {
        private static CalendarViewModel activeCalendar;

        public CalendarController(ICalendarRepository _calendarRepository, IEventRepository _eventRepository)
        {
            CalendarDomainModel.calendarRepository = _calendarRepository;
        }       

        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Create(CalendarViewModel calendarViewModel)
        {
            if (ModelState.IsValid)
            {
                calendarViewModel.userId = User.Identity.GetUserId();
                Calendar calendar = CalendarMapper.ToCalendar(calendarViewModel);
                calendar.ShowedDateTime = DateTime.Now;
                CalendarDomainModel.calendarRepository.Add(calendar);
                CalendarDomainModel.calendarRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            Calendar calendar = CalendarDomainModel.calendarRepository.FindById(id);
            if (Request.IsAjaxRequest())
            {
                return PartialView(CalendarMapper.ToCalendarViewModel(calendar));
            }
            else
            {
                return View(CalendarMapper.ToCalendarViewModel(calendar));
            }
        }

        [HttpPost]
        public ActionResult Edit(CalendarViewModel calendarViewModel)
        {
            if (ModelState.IsValid)
            {
                Calendar calendar = CalendarMapper.ToCalendar(calendarViewModel);
                calendar.UserId = User.Identity.GetUserId();
                if (calendarViewModel.calendarDateTime == null)
                {
                    calendar.ShowedDateTime = DateTime.Now;
                }
                else
                {
                    calendar.ShowedDateTime = calendarViewModel.calendarDateTime.GetDateTime();
                }
                CalendarDomainModel.calendarRepository.Modify(calendar);
                CalendarDomainModel.calendarRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            Calendar calendar = CalendarDomainModel.calendarRepository.FindById(id);
            CalendarDomainModel.calendarRepository.Delete(calendar);
            CalendarDomainModel.calendarRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ViewResult Index()
        {
            return View(CalendarDomainModel.GetCalendarViewModels(User.Identity.GetUserId()));
        }

        public PartialViewResult CalendarDayPartial(int id)
        {
            activeCalendar = SetCalendarAsActive(id);
            return PartialView("_CalendarDayPartial", activeCalendar);
        }

        public PartialViewResult CalendarWeekPartial(int id)
        {           
            activeCalendar = SetCalendarAsActive(id);
            return PartialView("_CalendarWeekPartial", activeCalendar);
        }

        public CalendarViewModel SetCalendarAsActive(int? id)
        {
            CalendarViewModel newActiveCalendar;

            if (id.HasValue)
            {
                newActiveCalendar = CalendarMapper.
                    ToCalendarViewModel(CalendarDomainModel.calendarRepository.FindById(id.Value));
            }
            else
            {
                newActiveCalendar = CalendarMapper.ToCalendarViewModel(CalendarDomainModel.calendarRepository.
                    GetUserCalendars(User.Identity.GetUserId()).ToList().FirstOrDefault());
            }

            return newActiveCalendar;
        }

        public ActionResult ShowMonth(int? id, int offset)
        {
            activeCalendar = SetCalendarAsActive(id);

            Calendar calendar = CalendarDomainModel.calendarRepository.FindById(id.Value);

            activeCalendar.calendarDateTime.AddMonth(offset);
            calendar.ShowedDateTime = activeCalendar.calendarDateTime.GetDateTime();
            CalendarDomainModel.calendarRepository.SaveChanges();

            return PartialView("_CalendarMonthPartial", activeCalendar);
        }       

        public ActionResult ShowNextPrevDay(int? id, int offset)
        {
            activeCalendar = SetCalendarAsActive(id);
            Calendar calendar = CalendarDomainModel.calendarRepository.FindById(id.Value);

            activeCalendar.calendarDateTime.AddDay(offset);
            calendar.ShowedDateTime = activeCalendar.calendarDateTime.GetDateTime();
            CalendarDomainModel.calendarRepository.SaveChanges();

            return PartialView("_CalendarDayPartial", activeCalendar);
        }       

        public ActionResult ShowDay(string Day)
        {
            if (activeCalendar == null) activeCalendar = SetCalendarAsActive(CalendarDomainModel.calendarRepository.GetUserCalendars(User.Identity.GetUserId()).First().Id);

            Calendar calendar = CalendarDomainModel.calendarRepository.FindById(activeCalendar.id);

            activeCalendar.calendarDateTime.SetDateTime(Convert.ToDateTime(Day));
            calendar.ShowedDateTime = activeCalendar.calendarDateTime.GetDateTime();
            CalendarDomainModel.calendarRepository.SaveChanges();

            return PartialView("_CalendarDayPartial", activeCalendar);
        }

        public ActionResult CalendarMonthPartial(int? id)
        {
            activeCalendar = SetCalendarAsActive(id);
            return PartialView("_CalendarMonthPartial", activeCalendar);
        }

        public string JSONIndex()
        {
            List<Calendar> data = CalendarDomainModel.calendarRepository.GetAll().ToList();
            return JsonConvert.SerializeObject(data);
        }

        public ActionResult Details(int id)
        {
            return View(CalendarDomainModel.GetDetails(id));
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

web_calendar/web_calendar/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using web_calendar.DAL.Models;
using web_calendar.Models;
using web_calendar.DAL.Interface;
using Newtonsoft.Json;
using System.Web.Services;
using web_calendar.BL.Mappers;
using web_calendar.BL.ViewModels;
using web_calendar.BL.ServerValidation;
using web_calendar.Handlers;
using System.Transactions;
using web_calendar.BL.DomainModels;

namespace web_calendar.Controllers
{
    [Authorize]
    //[CustomHandleErrorAttribute]
    public class EventController : Controller
    {
        private IEventRepository eventRepository;
        private INotificationRepository notificationRepository;
        private ICalendarRepository calendarRepository;
        private EventDomainModel eventDomainModel;

        public EventController(IEventRepository _eventRepository, INotificationRepository _notificationRepository,
            ICalendarRepository _calendarRepository, EventDomainModel _eventDomainModel)  
        {
            this.eventRepository = _eventRepository;
            this.notificationRepository = _notificationRepository;
            this.calendarRepository = _calendarRepository;
            this.eventDomainModel = new EventDomainModel(eventRepository, notificationRepository, calendarRepository);
        }

        public JsonResult GetNextNotification()
        {
            string userId = User.Identity.GetUserId();
            return Json(eventDomainModel.GetNextReminder(userId), JsonRequestBehavior.AllowGet);
        }

        // GET: Event/Schedule/2
        public ActionResult Schedule(int? id)
        {
            string userId = User.Identity.GetUserId();
            if (Request.IsAjaxRequest())
            {
                return PartialView("Schedule", eventDomainModel.GetFollowingEvents(id, userId));
            }
            else
            {
                return View("Schedule", eventDomainModel.GetFollowingEvents(id, userId));
            }
        }

        // GET: Event/Notify/2
        public ActionResult Notify(int id)
        {
            if (eventRepository.FindById(id) != null)
            {
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().
                    GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                eventDomainModel.SendInvitations(user.Email, user.UserName, id);
            }
            return RedirectToAction("Schedule");
        }

        // GET: Event/Details/5
        public ActionResult Details(int id)
        {
            CalendarEvent calendarEvent = eventRepository.FindById(id);
            if (calendarEvent == null)
            {
                return HttpNotFound();
            }
            return View(eventDomainModel.GetEventDetails(calendarEvent));
        }

        // GET: Event/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            CreateEventViewModel eventViewModel = new CreateEventViewModel();
            eventDomainModel.PopulateCalendarSelectList(ref eventViewModel, userId);
            if (Request.IsAjaxRequest())
            {
                return PartialView(eventViewModel);
            }
            else
            {
                return View(eventViewModel);
            }
        }

        // POST: Event/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEventViewModel eventViewModel)
        {
            string userId = User.Identity.GetUserId();
            int calendarId = eventViewModel.SelectedCalendarId;
            if (ModelState.IsValid)
            {
                switch (EventValidator.Validate(eventViewModel))
                {
                    case 0:
                        if (eventRepository.FindOtherById<Calendar>(calendarId) != null)
                        {
                            eventDomainModel.CreateEvent(eventViewModel, calendarId);
                            return RedirectToAction("Schedule");
                        }
                        break;
                    case 1:
                        ModelState.AddModelError("Name", "Name is required.");
                        break;
                    case 2:
                        ModelState.AddModelError("Begin time", "Begin time is required.");
                        break;
                    case 3:
                        ModelState.AddModelError("", "All notifications must have specified time before event.");
                        break;
                    case 4:
                        ModelState.AddModelError("", "All guests must have an email.");
                        break;
                }
            }
            eventDomainModel.PopulateCalendarSelectList(ref eventViewModel, userId);
            return View(eventViewModel);
        }

        /*
        public ActionResult CreateByRef(string eventByRef)
        {
            CreateEventViewModel eventViewModel = JsonConvert.DeserializeObject<CreateEventViewModel>(eventByRef);           
            string userId = User.Identity.GetUserId();
            eventDomainModel.PopulateCalendarSelectList(ref eventViewModel, userId);
            return View("Create",eventViewModel);
        }*/

        // GET: Event/Edit/5
        public ActionResult Edit(int id)
        {
            string userId = User.Identity.GetUserId();
            CalendarEvent calendarEvent = eventRepository.FindById(id);
            if (calendarEvent == null)
            {
                return HttpNotFound();
            }
            CreateEventViewModel eventViewModel = eventDomainModel.GetEditEventViewModel(calendarEvent);
            eventViewModel.CalendarItems = new SelectList(
                calendarRepository.GetUserCalendars(userId).Select(
                x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList(), "Value", "Text",
                calendarEvent.CalendarId.ToString());
            eventViewModel.SelectedCalendarId = calendarEvent.CalendarId.Value;
            return View(eventViewModel);
        }

        // POST: Event/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CreateEventViewModel eventViewModel)
        {
            string userId = User.Identity.GetUserId();
            int calendarId = eventViewModel.SelectedCalendarId;
            if (ModelState.IsValid)
            {
                switch (EventValidator.Validate(eventViewModel))
                {
                    case 0:
                        eventDomainModel.EditEvent(id, eventViewModel, calendarId);
                        return RedirectToAction("Schedule");                        
                    case 1:
                        ModelState.AddModelError("Name", "Name is required.");
                        break;
                    case 2:
                        ModelState.AddModelError("Begin time", "Begin time is required.");
                        break;
                    case 3:
                        ModelState.AddModelError("", "All notifications must have specified time before event.");
                        break;
                    case 4:
                        ModelState.AddModelError("", "All guests must have an email.");
                        break;
                }
            }
            eventViewModel.CalendarItems = new SelectList(
                calendarRepository.GetUserCalendars(userId).Select(
                x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList(), "Value", "Text",
                calendarId);
            eventViewModel.CalendarItems.First().Selected = true;
            eventViewModel.SelectedCalendarId = calendarId;
            return View(eventViewModel);
        }

        public ActionResult GetNotificationView(int id)
        {
            NotificationViewModel notificationVM = new NotificationViewModel();
            notificationVM.Id = id;
            notificationVM.MyPrefix = "Notifications[" + id + "]";
            return PartialView("_EditNotification", notificationVM);
        }

        public ActionResult GetGuestView(int id)
        {
            GuestsEmail guestVM = new GuestsEmail();
            guestVM.Id = id;
            guestVM.MyPrefix = "Guests[" + id + "]";
            return PartialView("_EditGuest", guestVM);
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int id)
        {
            CalendarEvent calendarEvent = eventRepository.FindById(id);
            if (calendarEvent == null)
            {
                return HttpNotFound();
            }
            DisplayEventViewModel eventViewModel = EventMapper.MapToDisplayEventVM(calendarEvent);
            return View(eventViewModel);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            eventDomainModel.DeleteEvent(id);
            return RedirectToAction("Schedule");
        }
    }
}

web_calendar/web_calendar/Views/Calendar/CalendarList.cshtml
@model IEnumerable<web_calendar.BL.ViewModels.CalendarViewModel>
@using Newtonsoft.Json

<script src="~/Scripts/customScripts.js"></script>
<div id="results">
    <table class="table" style="width:200px">
        <tr>
            <th colspan="2">My Calendars</th>
        </tr>

        @if (Model != null)
        {
            foreach (var calendar in Model)
            {
                <tr>
                    <td>
                        <script type="text/javascript">
                            var data = @Html.Raw(JsonConvert.SerializeObject(calendar));
                            
                        </script>
                        @Ajax.ActionLink(calendar.name, "CalendarMonthPartial", new { id = calendar.id }, new AjaxOptions { UpdateTargetId = "calendarContainer" })
                    </td>
                    <td>
                        @Ajax.ActionLink(" ", "Edit", new { id = calendar.id }, new AjaxOptions { UpdateTargetId = "mainWindow" }, new { @class = "glyphicon glyphicon-edit" })                        
                        
                        @Ajax.ActionLink(" ", "Delete", new { id = calendar.id }, new AjaxOptions
                                        {
                                            Confirm = "Are you sure you wish to delete this calendar?",
                                            UpdateTargetId = "mainWindow",
                                        }, new { @class = "glyphicon glyphicon-remove" })                                              

                        @Html.ActionLink(" ", "Schedule", "Event", new { id = calendar.id }, new { @class = "glyphicon glyphicon-list-alt" })
                    </td>
                </tr>
            }
        }
    </table>
</div>

web_calendar/web_calendar/Views/Calendar/Create.cshtml
@model web_calendar.BL.ViewModels.CalendarViewModel

@{
    ViewBag.Title = "Create calendar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <br />
            <h3 class="control-label col-md-2" style="color: gray;">Create сalendar</h3>
            <br />
            <br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "required-label control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, htmlAttributes: new { @class = "form-control", @rows = "3", @resize = "none" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.calendarColor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.calendarColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.calendarColor, "", new { @class = "text-danger" })
            </div>
        </div>      

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                &nbsp;
               @Html.ActionLink("Cancel", "Index", "Calendar", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

web_calendar/web_calendar/Views/Calendar/Details.cshtml
@model web_calendar.BL.ViewModels.CalendarViewModel

<div>
    <h4>Calendar details</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.calendarColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.calendarColor)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

web_calendar/web_calendar/Views/Calendar/Edit.cshtml
@model web_calendar.BL.ViewModels.CalendarViewModel

@{
    ViewBag.Title = "Edit calendar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <br />
            <h3 class="control-label col-md-2" style="color: gray;">Edit сalendar</h3>
            <br />
            <br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "required-label control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, htmlAttributes: new { @class = "form-control", @rows = "3", @resize = "none" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.calendarColor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.calendarColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.calendarColor, "", new { @class = "text-danger" })
            </div>
        </div>
 
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                &nbsp;
                @Html.ActionLink("Cancel", "Index", "Calendar", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

web_calendar/web_calendar/Views/Calendar/GetCalendars.cshtml
@model IEnumerable<web_calendar.BL.ViewModels.CalendarViewModel>
@using Newtonsoft.Json

    <script src="~/Scripts/customScripts.js"></script>
    <div id="results">
            <table class="table" style="width:10%">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.name)
                    </th>
                </tr>

                @if (Model != null)
                {
                    foreach (var calendar in Model)
                    {
                        <tr>
                            <td>
                                <script type="text/javascript">
                                    var data = @Html.Raw(JsonConvert.SerializeObject(calendar))
                                    Add(data);
                                </script>
                            </td>
                            <td>
                                @Ajax.ActionLink(calendar.name, "CalendarMonthPartial", new { id = calendar.id }, new AjaxOptions { UpdateTargetId = "calendarContainer" })
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = calendar.id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = calendar.id }) |
                                @Html.ActionLink("Schedule", "Schedule", "Event", new { id = calendar.id }, htmlAttributes: new { @class = "" })
                            </td>
                        </tr>
                    }
                }
            </table>
    </div>

web_calendar/web_calendar/Views/Calendar/Index.cshtml
@model IEnumerable<web_calendar.BL.ViewModels.CalendarViewModel>

@{
    ViewBag.Title = "Calendar";
}

<div class="calendarWrapper">
    <div class="miniCalendarContainer">
        <div id="datetimepicker"></div>
        <script type="text/javascript">            
            $("#datetimepicker").datepicker(
                {
                    inline: true,
                    format: "dd-mm-yyyy"
                }
            ).on("changeDate", function () {
                var dateObject = $("#datetimepicker").datepicker("getDate");
                var dateString = dateObject.getDate() + "-" + (dateObject.getMonth() + 1) + "-" + dateObject.getFullYear();
                $.ajax({
                    url: '@Url.Action("ShowDay", "Calendar")',
                    type: "get",
                    data: {Day: dateString},
                    success: function(data) {
                        document.getElementById("calendarContainer").innerHTML = data;
                        loadScript();                       
                    }
                });
            });
        </script>
        @Html.Partial("CalendarList")
    </div>

    <div class="calendarContainer" id="calendarContainer">
        @Html.Action("CalendarMonthPartial", new { id = Model.FirstOrDefault().id })
    </div>
</div>

web_calendar/web_calendar/Views/Calendar/JSONIndex.cshtml
<!--It`s temporary view-->

web_calendar/web_calendar/Views/Calendar/_CalendarDayPartial.cshtml
@model web_calendar.BL.ViewModels.CalendarViewModel

<div class="navigationCalendarContainer">
    <div class="leftNav">
        @Ajax.ActionLink("Day", "CalendarDayPartial", new { id = Model.id }, new AjaxOptions { UpdateTargetId = "calendarContainer" }, new { @class = "btn btn-primary btn-xs" })
        @Ajax.ActionLink("Week", "CalendarWeekPartial", new { id = Model.id, offset = 0 }, new AjaxOptions { UpdateTargetId = "calendarContainer" }, new { @class = "btn btn-primary btn-xs" })
        @Ajax.ActionLink("Month", "CalendarMonthPartial", new { id = Model.id }, new AjaxOptions { UpdateTargetId = "calendarContainer" }, new { @class = "btn btn-primary btn-xs" })
        @Html.ActionLink("Schedule", "Schedule", "Event", new { id = Model.id }, new { @class = "btn btn-primary btn-xs" })
    </div>
    <div class="rightNav">
        @Ajax.ActionLink("<", "ShowNextPrevDay", new { id = Model.id, offset = -1 }, new AjaxOptions { UpdateTargetId = "calendarContainer" })
        @Ajax.ActionLink(">", "ShowNextPrevDay", new { id = Model.id, offset = 1 }, new AjaxOptions { UpdateTargetId = "calendarContainer" })
        @Model.calendarDateTime.GetDay() @Model.calendarDateTime.GetMonthName() @Model.calendarDateTime.GetYear()
    </div>
</div>
<div class="calendarDayTable">
    <div class="fixedHeader">
        <div class="dayHeadRow">
            <div class="timeColTd"></div>
            <div class="dayBodyTd">
                @foreach (var calendarEvent in Model.eventList)
                {
                    if (calendarEvent.TimeBegin.Day == Model.calendarDateTime.GetDay())
                    {
                        if (calendarEvent.AllDay.HasValue && calendarEvent.AllDay.Value)
                        {
                            @calendarEvent.Name;
                                                   break;
                        }
                    }
                }
            </div>
        </div>
    </div>

    <div class="scrollCalendar">
        @for (int i = 0; i < 24; i++)
        {
            <div>
                <div class="timeColTd">@String.Format("{0:D2}:00", i)</div>
                <div class="dayBodyTd">
                    @{
                        bool flag = false;
                        foreach (var calendarEvent in Model.eventList)
                        {
                            if (calendarEvent.TimeBegin.Day == Model.calendarDateTime.GetDay())
                            {
                                <div>
                                    @if (calendarEvent.TimeBegin.Hour == i)
                                    {
                                        <div class="calendarEvent">@calendarEvent.Name;</div>
                                        flag = true;
                                    }
                                </div>
                            }
                        }
                        if (!flag)
                        {
                            <p>@string.Empty</p>
                        }
                    }
                </div>
            </div>
        }
    </div>
    <script type="text/javascript">
        loadScript();
        var model;
        function loadScript() {
            model = @Html.Raw(Json.Encode(Model));
            setColor(document.querySelectorAll(".calendarEvent"), model.CSSHeadColor);
            setColor(document.querySelectorAll(".dayBodyTd"), model.CSSMainColor);
            setColor(document.querySelectorAll(".timeColTd"), model.CSSHeadColor);
        };
    </script>
</div>